# Generated by Django 4.2.6 on 2024-05-16 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id_konten', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_podcaster', models.EmailField(max_length=254)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('id_konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id_episode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('durasi', models.IntegerField()),
                ('tanggal_rilis', models.DateField()),
                ('id_konten_podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
            ],
        ),
    ]
