# Generated by Django 4.2.6 on 2024-05-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id_konten',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
